import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Unity, useUnityContext } from "react-unity-webgl";
import { useEffect } from "react";

const Home: NextPage = () => {
  const { unityProvider, sendMessage } = useUnityContext({
    loaderUrl: "assets/the-greg-and-larry-show-webgl.loader.js",
    dataUrl: "assets/the-greg-and-larry-show-webgl.data",
    frameworkUrl: "assets/the-greg-and-larry-show-webgl.framework.js",
    codeUrl: "assets/the-greg-and-larry-show-webgl.wasm",
  });

  useEffect(() => {}, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>The Greg and Larry Show</title>
        <meta name="description" content="Generated by Logan Thomas" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {false && (
          <Unity
            style={{ height: "100vh", width: "100vw" }}
            unityProvider={unityProvider}
          />
        )}
      </div>
    </div>
  );
};

export default Home;
