import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Registration.module.css";
import { Button, Grid, TextField, Typography } from "@mui/material";
import { Container } from "@mui/system";
import Link from "next/link";
import { useState } from "react";
import axios from "axios";

const defaultFormData = {
  firstName: "",
  lastName: "",
  email: "",
  password: "",
  passwordConfirmation: "",
};

const Registration: NextPage = () => {
  const [formData, setFormData] = useState(defaultFormData);

  const handleChange = (field: string, value: string) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
  };

  const handleReset = () => {
    setFormData(defaultFormData);
  };

  const handleRegister = (formData: any) => {
    axios
      .post("https://localhost:7004/Auth/register", formData)
      .then((result) => {
        console.log("result:", result);
      })
      .catch((e) => {
        console.log("error:", e);
      });
  };

  console.log(formData);

  return (
    <div className={styles.container}>
      <Head>
        <title>The Greg and Larry Show - Registration</title>
        <meta name="description" content="Generated by Logan Thomas" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth="md">
        <Typography>Register</Typography>
        <Grid container xs={12} spacing={2}>
          <Grid item xs={6}>
            <TextField
              value={formData.firstName}
              onChange={(e) => handleChange("firstName", e.target.value)}
              label="First name"
            />
          </Grid>
          <Grid item xs={6}>
            <TextField
              value={formData.lastName}
              onChange={(e) => handleChange("lastName", e.target.value)}
              label="Last name"
            />
          </Grid>
          <Grid item xs={12}>
            <TextField
              value={formData.email}
              onChange={(e) => handleChange("email", e.target.value)}
              label="Email"
            />
          </Grid>
          <Grid item xs={6}>
            <TextField
              value={formData.password}
              onChange={(e) => handleChange("password", e.target.value)}
              type="password"
              label="Password"
            />
          </Grid>
          <Grid item xs={6}>
            <TextField
              value={formData.passwordConfirmation}
              onChange={(e) =>
                handleChange("passwordConfirmation", e.target.value)
              }
              type="password"
              label="Re-enter password"
            />
          </Grid>
          <Grid item xs={6}>
            <Button
              onClick={() => handleRegister(formData)}
              variant="contained"
              fullWidth
            >
              Register
            </Button>
          </Grid>
          <Grid item xs={6}>
            <Link href={`/play`}>
              <Button color="warning" variant="contained" fullWidth>
                Continue without saving
              </Button>
            </Link>
          </Grid>
          <Grid item xs={12}>
            <Link href={`/login`}>
              <Button variant="contained" color="secondary" fullWidth>
                Already have an account? Login
              </Button>
            </Link>
          </Grid>
        </Grid>
      </Container>
    </div>
  );
};

export default Registration;
