import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Registration.module.css";
import { Unity, useUnityContext } from "react-unity-webgl";
import { useEffect } from "react";
import { Button, createTheme, Grid, TextField } from "@mui/material";
import { Container } from "@mui/system";
import { RegistrationForm } from "../components/RegistrationForm";

const Registration: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>The Greg and Larry Show</title>
        <meta name="description" content="Generated by Logan Thomas" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div className="container"> */}
      <RegistrationForm />
      {/* </div> */}
    </div>
  );
};

export default Registration;
